import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="relative z-0 mx-auto flex max-w-7xl flex-col justify-between px-4 py-8 sm:px-6 lg:px-8">
          <Header></Header>
          {children}
        </main>
      </body>
    </html>
  );
}
